// Generated by ts-to-zod
import { z } from "zod";

export const mealFoodsIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.meal_foods"),
  }),
);

const mealsIdSchema = z.any();

const foodsIdSchema = z.any();

const foodVariantsIdSchema = z.any();

export const mealFoodsSchema = z.object({
  id: mealFoodsIdSchema,
  meal_id: mealsIdSchema,
  food_id: foodsIdSchema,
  variant_id: foodVariantsIdSchema.nullable(),
  quantity: z.number(),
  unit: z.string(),
  created_at: z.date(),
  updated_at: z.date(),
});

export const mealFoodsInitializerSchema = z.object({
  id: mealFoodsIdSchema.optional(),
  meal_id: mealsIdSchema,
  food_id: foodsIdSchema,
  variant_id: foodVariantsIdSchema.optional().nullable(),
  quantity: z.number(),
  unit: z.string(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export const mealFoodsMutatorSchema = z.object({
  id: mealFoodsIdSchema.optional(),
  meal_id: mealsIdSchema.optional(),
  food_id: foodsIdSchema.optional(),
  variant_id: foodVariantsIdSchema.optional().nullable(),
  quantity: z.number().optional(),
  unit: z.string().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export type MealFoods = z.infer<typeof mealFoodsSchema>;
export type MealFoodsInitializer = z.infer<typeof mealFoodsInitializerSchema>;
export type MealFoodsMutator = z.infer<typeof mealFoodsMutatorSchema>;
