import {
  ExerciseEntryResponse,
  ExerciseSessionResponse,
  ExerciseSnapshotResponse,
  PresetSessionResponse,
  IndividualSessionResponse,
} from '@workspace/shared';

export interface ActivityDetailKeyValuePair {
  id?: string; // Optional for new entries, will be generated by backend
  key: string; // Maps to detail_type in backend
  value: string; // Stored within detail_data as JSONB in backend
  detail_data?: unknown;
  provider_name?: string; // Optional, will default to 'Manual' in backend
  detail_type?: string; // Optional, will default to 'Custom Field' in backend
}

export type GroupedExerciseEntry = ExerciseSessionResponse;

export type ExerciseEntry = ExerciseEntryResponse;

export type Exercise = ExerciseSnapshotResponse;

export type PresetSessionEntry = PresetSessionResponse;
export type IndividualSessionEntry = IndividualSessionResponse;

export interface HistoryImportEntry {
  entry_date: string;
  id: string;
  exercise_name: string;
  preset_name?: string;
  entry_notes?: string;
  calories_burned?: number;
  distance?: number;
  avg_heart_rate?: number;
  exercise_category?: string;
  calories_per_hour?: number;
  exercise_description?: string;
  exercise_source?: string;
  exercise_force?: string;
  exercise_level?: string;
  exercise_mechanic?: string;
  exercise_equipment?: string[];
  primary_muscles?: string[];
  secondary_muscles?: string[];
  instructions?: string[];
  sets?: {
    set_number: number;
    set_type?: string;
    reps?: number;
    weight?: number;
    duration_min?: number;
    rest_time_sec?: number;
    notes?: string;
  }[];
  activity_details?: unknown[];
}

export interface ExerciseDeletionImpact {
  exerciseEntriesCount: number;
  // server returns counts; normalize to a boolean for backward compatible UI use
  isUsedByOthers: boolean;
  otherUserReferences?: number;
}

export type ExerciseOwnershipFilter =
  | 'all'
  | 'own'
  | 'family'
  | 'public'
  | 'needs-review';

export interface LapDTO {
  lapIndex?: number;
  distance?: number;
  duration?: number;
  movingDuration?: number;
  elapsedDuration?: number;
  averageSpeed?: number;
  averageMovingSpeed?: number;
  maxSpeed?: number;
  averageHR?: number;
  maxHR?: number;
  averageRunCadence?: number;
  maxRunCadence?: number;
  calories?: number;
  elevationGain?: number;
  elevationLoss?: number;
  [key: string]: unknown;
}

export interface ActivityDetailsResponse {
  id?: string;
  activity?: {
    details?: {
      metricDescriptors?: unknown[];
      activityDetailMetrics?: ActivityDetailMetric[];
      geoPolylineDTO?: {
        polyline: { lat: number; lon: number }[];
      };
      [key: string]: unknown;
    };
    hr_in_timezones?: unknown[];
    splits?: {
      lapDTOs: LapDTO[];
      [key: string]: unknown;
    };
    // All provider field names are covered via [key: string]: unknown,
    // but common ones are listed for type-safety in shared code.
    activity?: {
      // Garmin
      duration?: number;
      calories?: number;
      active_calories?: number;
      totalAscent?: number;
      elevationGain?: number;
      averageHR?: number;
      averageRunCadence?: number;
      averageRunCadenceInStepsPerMinute?: number;
      distance?: number;
      averagePace?: number;
      averageSpeed?: number;
      activityName?: string;
      activityType?: { typeKey?: string; [key: string]: unknown };
      eventType?: unknown;
      course?: unknown;
      gear?: unknown;
      // Strava
      name?: string;
      moving_time?: number;
      elapsed_time?: number;
      average_heartrate?: number;
      average_cadence?: number;
      average_speed?: number;
      total_elevation_gain?: number;
      sport_type?: string;
      // Fitbit
      averageHeartRate?: number;
      [key: string]: unknown;
    };
    [key: string]: unknown;
  };
  workout?: {
    workoutName: string;
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

export interface ActivityDetailMetric {
  metrics: string[];
}

export interface CsvRow {
  entry_date: string;
  exercise_name: string;
  preset_name?: string;
  entry_notes?: string;
  calories_burned?: string;
  distance?: string;
  avg_heart_rate?: string;
  set_number?: string;
  set_type?: string;
  reps?: string;
  weight?: string;
  duration_min?: string;
  rest_time_sec?: string;
  set_notes?: string;
  exercise_category?: string;
  calories_per_hour?: string;
  exercise_description?: string;
  exercise_source?: string;
  exercise_force?: string;
  exercise_level?: string;
  exercise_mechanic?: string;
  exercise_equipment?: string;
  primary_muscles?: string;
  secondary_muscles?: string;
  instructions?: string;
  activity_field_name?: string;
  activity_value?: string;
  [key: string]: string | undefined;
}

export interface HistoryGroupedExerciseEntry {
  id: string;
  entry_date: Date;
  exercise_name: string;
  preset_name?: string;
  entry_notes?: string;
  calories_burned?: number;
  distance?: number;
  avg_heart_rate?: number;
  exercise_category?: string;
  calories_per_hour?: number;
  exercise_description?: string;
  exercise_source?: string;
  exercise_force?: string;
  exercise_level?: string;
  exercise_mechanic?: string;
  exercise_equipment?: string[];
  primary_muscles?: string[];
  secondary_muscles?: string[];
  instructions?: string[];
  sets: {
    set_number: number;
    set_type?: string;
    reps?: number;
    weight?: number;
    duration_min?: number;
    rest_time_sec?: number;
    notes?: string;
  }[];
  activity_details: {
    field_name: string;
    value: string | number;
  }[];
}
