// Generated by ts-to-zod
import { z } from "zod";

export const backupSettingsSchema = z.object({
  id: z.number().optional(),
  backupEnabled: z.boolean(),
  backupDays: z.array(z.string()),
  backupTime: z.string(),
  retentionDays: z.number(),
  lastBackupStatus: z.string().nullable(),
  lastBackupTimestamp: z.coerce.date().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export const backupSettingsInitializerSchema = z.object({
  id: z.number().optional(),
  backupEnabled: z.boolean().optional(),
  backupDays: z.array(z.string()).optional(),
  backupTime: z.string().optional(),
  retentionDays: z.number().optional(),
  lastBackupStatus: z.string().optional().nullable(),
  lastBackupTimestamp: z.date().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export const backupSettingsMutatorSchema = z.object({
  id: z.number().optional(),
  backupEnabled: z.boolean().optional(),
  backupDays: z.array(z.string()).optional(),
  backupTime: z.string().optional(),
  retentionDays: z.number().optional(),
  lastBackupStatus: z.string().optional().nullable(),
  lastBackupTimestamp: z.date().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export type BackupSettings = z.infer<typeof backupSettingsSchema>;
export type BackupSettingsInitializer = z.infer<
  typeof backupSettingsInitializerSchema
>;
export type BackupSettingsMutator = z.infer<typeof backupSettingsMutatorSchema>;
