// Generated by ts-to-zod
import { z } from "zod";

export const userWaterContainersIdSchema = z.number().and(
  z.object({
    __brand: z.literal("public.user_water_containers"),
  }),
);

const userIdSchema = z.any();

export const userWaterContainersSchema = z.object({
  id: userWaterContainersIdSchema,
  user_id: userIdSchema,
  name: z.string(),
  volume: z.number(),
  unit: z.string(),
  is_primary: z.boolean().nullable(),
  created_at: z.date(),
  updated_at: z.date(),
  servings_per_container: z.number(),
});

export const userWaterContainersInitializerSchema = z.object({
  id: userWaterContainersIdSchema.optional(),
  user_id: userIdSchema,
  name: z.string(),
  volume: z.number(),
  unit: z.string(),
  is_primary: z.boolean().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  servings_per_container: z.number().optional(),
});

export const userWaterContainersMutatorSchema = z.object({
  id: userWaterContainersIdSchema.optional(),
  user_id: userIdSchema.optional(),
  name: z.string().optional(),
  volume: z.number().optional(),
  unit: z.string().optional(),
  is_primary: z.boolean().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  servings_per_container: z.number().optional(),
});

export type UserWaterContainers = z.infer<typeof userWaterContainersSchema>;
export type UserWaterContainersInitializer = z.infer<typeof userWaterContainersInitializerSchema>;
export type UserWaterContainersMutator = z.infer<typeof userWaterContainersMutatorSchema>;
